;; -*- lexical-binding: t -*-
(require 'copilot)
(add-hook 'ruby-ts-mode-hook 'copilot-mode)
(add-hook 'emacs-lisp-mode-hook 'copilot-mode)
(add-hook 'java-ts-mode-hook 'copilot-mode)
(add-hook 'rust-ts-mode-hook 'copilot-mode)
(add-hook 'tsx-ts-mode-hook 'copilot-mode)
(add-hook 'typescript-ts-mode-hook 'copilot-mode)
(add-hook 'js-ts-mode-hook 'copilot-mode)
(add-hook 'css-ts-mode-hook 'copilot-mode)

(define-key copilot-completion-map (kbd "TAB") #'indent-for-tab-command)
(define-key copilot-completion-map (kbd "<tab>") #'indent-for-tab-command)
(define-key copilot-completion-map (kbd "C-c C-y") #'copilot-accept-completion)
(add-to-list 'copilot-major-mode-alist '("ruby-ts-mode" . "ruby"))
(add-to-list 'copilot-major-mode-alist '("emacs-lisp-mode" . "elisp"))
(add-to-list 'copilot-major-mode-alist '("java-ts-mode" . "java"))
(add-to-list 'copilot-major-mode-alist '("rust-ts-mode" . "rust"))
(add-to-list 'copilot-major-mode-alist '("tsx-ts-mode" . "typescriptreact"))
(add-to-list 'copilot-major-mode-alist '("typescript-ts-mode" . "typescript"))
(add-to-list 'copilot-major-mode-alist '("js-ts-mode" . "javascript"))
(add-to-list 'copilot-major-mode-alist '("css-ts-mode" . "css"))
