(setq 4k '(3840 2160))
(setq fhd '(1920 1080))
(setq default-font-height 140)

(cond ((and (= (display-pixel-width) 10)
            (= (display-pixel-height) 9))
       (setq font-height default-font-height))
      ((and (>= (display-pixel-width) (nth 0 4k))
            (>= (display-pixel-height) (nth 1 4k)))
       (setq font-height 140))
      ((and (>= (display-pixel-width) (nth 0 fhd))
            (>= (display-pixel-height) (nth 1 fhd)))
       (setq font-height 120))
      ((and (<  (display-pixel-width) (nth 0 fhd))
            (<  (display-pixel-height) (nth 1 fhd)))
       (setq font-height 100)))

(set-face-attribute 'default nil :family "Noto Sans Mono CJK JP" :height font-height)

(global-set-key (kbd "s-C-u") 'text-scale-increase)
(global-set-key (kbd "s-C-l") 'text-scale-decreae)
(global-set-key (kbd "s-C-0") 'text-scale-adjust)
