(autoload 'haml-mode    "haml-mode" "edit haml sources")
(autoload 'slim-mode    "slim-mode" "edit slim sources")
(autoload 'web-mode     "web-mode"  "edit erb sources" )
(autoload 'sass-mode    "sass-mode" "edit sass sources")
(autoload 'coffee-mode  "coffee-mode" "edit coffeescript sources")
(autoload 'feature-mode "feature-mode" "edit feature sources")

(custom-set-variables '(coffee-tab-width 2))
(add-to-list 'auto-mode-alist '("\\.haml$" . haml-mode))
(add-to-list 'auto-mode-alist '("\\.slim$" . slim-mode))
(add-to-list 'auto-mode-alist '("\\.erb$" . web-mode))
(add-to-list 'auto-mode-alist '("\\.sass$" . sass-mode))
(add-to-list 'auto-mode-alist '("\\.coffee$" . coffee-mode))
(add-to-list 'auto-mode-alist '("\\.feature$" . feature-mode))
(add-hook 'coffee-mode-hook
          '(lambda ()
             (setq flycheck-checker 'coffee)
             (flycheck-mode 1)))
(add-hook 'web-mode-hook
          '(lambda ()
             (setq web-mode-markup-indent-offset 2)))

(define-key global-map (kbd "M-p M-c") 'helm-rails-controllers)
(define-key global-map (kbd "M-p M-m") 'helm-rails-models)
(define-key global-map (kbd "M-p M-u") 'helm-rails-views)
(define-key global-map (kbd "M-p M-s") 'helm-rails-specs)
(define-key global-map (kbd "M-p M-r") 'helm-rails-all)
