(autoload 'haml-mode    "haml-mode" "edit haml sources")
(autoload 'slim-mode    "slim-mode" "edit slim sources")
(autoload 'sass-mode    "sass-mode" "edit sass sources")
(autoload 'coffee-mode  "coffee-mode" "edit coffeescript sources")
(autoload 'feature-mode "feature-mode" "edit feature sources")
(require  'flymake-coffee)

(custom-set-variables '(coffee-tab-width 2))
(add-to-list 'auto-mode-alist '("\\.haml$" . haml-mode))
(add-to-list 'auto-mode-alist '("\\.slim$" . slim-mode))
(add-to-list 'auto-mode-alist '("\\.sass$" . sass-mode))
(add-to-list 'auto-mode-alist '("\\.coffee$" . coffee-mode))
(add-to-list 'auto-mode-alist '("\\.feature$" . feature-mode))
(add-hook 'coffee-mode-hook 'flymake-coffee-load)
(add-hook 'feature-mode-hook 'flycheck-mode)

(define-key global-map (kbd "M-p M-c") 'helm-rails-controllers)
(define-key global-map (kbd "M-p M-m") 'helm-rails-models)
(define-key global-map (kbd "M-p M-u") 'helm-rails-views)
(define-key global-map (kbd "M-p M-s") 'helm-rails-specs)
(define-key global-map (kbd "M-p M-r") 'helm-rails-all)
