;; (cond ((string-match "freebsd" system-configuration)
;;    (require 'twittering-mode)) )
;;(setq twittering-username "katsyoshi")))
;;(setq twittering-password "")))
;;(add-to-list 'load-path "~/.emacs.d/site-lisp/twittering-mode/")
(require 'twittering-mode)
(setq twittering-auth-method 'xauth)
;;(setq twittering-username "")
;;(setq twittering-password "")

